language: php

php: [5.4, 5.5, hhvm]

install:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then composer update ; fi
  - if [[ $TRAVIS_PHP_VERSION == 'hhvm' ]]; then composer update php phpspec/phpspec; fi

script:
  - bin/phpspec run --format=pretty --no-code-generation
  - bin/behat
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then bin/coveralls -v ; fi


notifications:
  - email:
    on_success: change
    on_failure: change

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm