language: php

php: [5.4, 5.5, hhvm]

before_script:
  - composer install

script:
  - bin/phpspec run --format=pretty
  - phpunit
  
after_script:
  - bin/coveralls -v

notifications:
  - email:
    on_success: change
    on_failure: change
	
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true