language: php

php: [5.4, 5.5, hhvm]

before_install:
  # Remove code coverage in hhvm
  - if [[ $TRAVIS_PHP_VERSION == 'hhvm' ]]; then sed -i "s/ - PhpSpec\\\Extension\\\CodeCoverageExtension//" phpspec.yml ; fi
  - if [[ $TRAVIS_PHP_VERSION == 'hhvm' ]]; then composer remove henrikbjorn/phpspec-code-coverage satooshi/php-coveralls --dev --no-update ; fi

install:
  - composer update --dev

script:
  - bin/phpspec run --format=pretty --no-code-generation
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then bin/behat ; fi
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then bin/coveralls -v ; fi

notifications:
  - email:
    on_success: change
    on_failure: change

matrix:
  fast_finish: true
